language: node_js
cache: 
  directories:
    - node_modules
    - ~/.npm
  node_js:
    - '12'
  git:
    depth: 3
  script:
    - yarn build
  notifications:
    email: 
      recipients:
       - cabrerabaldera@gmail.com
       on_success: always
       on_failure: always
  deploy:
    provider: pages
    edge: true
    skip-cleanup: true
    keep-history: true
    github-token: $GITHUB_TOKEN
    local-dir: dist/
    target-brach: gh-pages
    commit-message: "Deploy del proyecto"
    on:
      branch: main